"""added forgot password functionality

Revision ID: 6161c1570547
Revises: 71f9a4975765
Create Date: 2026-03-16 10:58:07.959727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6161c1570547'
down_revision: Union[str, Sequence[str], None] = '71f9a4975765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_reset_password',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forgot_password_otp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forgot_password_otp')
    op.drop_table('allowed_reset_password')
    # ### end Alembic commands ###
