"""added expires field to signup otp

Revision ID: 6ab1304fb160
Revises: 8317ede36a75
Create Date: 2026-03-12 14:22:06.528675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ab1304fb160'
down_revision: Union[str, Sequence[str], None] = '8317ede36a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_otp', sa.Column('expires', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup_otp', 'expires')
    # ### end Alembic commands ###
