"""hashed otps

Revision ID: 71f9a4975765
Revises: c03805ea4282
Create Date: 2026-03-13 07:04:46.729047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from src.utils.otp import generate_otp_hash

# revision identifiers, used by Alembic.
revision: str = '71f9a4975765'
down_revision: Union[str, Sequence[str], None] = 'c03805ea4282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_otp', sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    connection = op.get_bind()

    result_proxy = connection.execute(sa.text("SELECT id, otp FROM signup_otp"))

    chunk_size = 1000

    while True:

        chunk = result_proxy.fetchmany(chunk_size)

        if not chunk:
            break

        batch_update = []

        
        for row in chunk:
            raw_id = row._mapping["id"]
            raw_otp = row._mapping["otp"]

            otp_hash = generate_otp_hash(raw_otp)
            batch_update.append({"otp_hash": otp_hash, "id": raw_id})

        if batch_update:
            connection.execute(sa.text("UPDATE signup_otp SET otp_hash = :otp_hash WHERE id = :id"), batch_update)

    op.alter_column('signup_otp','otp_hash', nullable=False)

    op.drop_column('signup_otp', 'otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_otp', sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('signup_otp', 'otp_hash')
    # ### end Alembic commands ###
