"""made expires field non nullable

Revision ID: c03805ea4282
Revises: dce732830070
Create Date: 2026-03-13 03:58:20.808747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c03805ea4282'
down_revision: Union[str, Sequence[str], None] = 'dce732830070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    op.execute(sa.text(
        """ 
        UPDATE signup_otp 
        SET expires = created_at + INTERVAL '10 minutes'
        WHERE expires IS NULL
"""
    ))

    op.alter_column('signup_otp', 'expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signup_otp', 'expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
