"""added id to signup otp and made primary key

Revision ID: dce732830070
Revises: 6ab1304fb160
Create Date: 2026-03-13 02:41:22.420532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import text

# revision identifiers, used by Alembic.
revision: str = 'dce732830070'
down_revision: Union[str, Sequence[str], None] = '6ab1304fb160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_otp', sa.Column('id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###

    op.execute(text("UPDATE signup_otp SET id = gen_random_uuid()"))

    op.alter_column('signup_otp', 'id', nullable=False)

    op.drop_constraint('signup_otp_pkey', 'signup_otp', type_='primary')

    op.create_primary_key('pk_signup_otp', 'signup_otp', ['id'])

def downgrade() -> None:
    """Downgrade schema."""

    op.drop_constraint('pk_signup_otp', 'signup_otp', type_='primary')    

    op.create_primary_key('signup_otp_pkey', 'signup_otp', ['uid'])
   
    op.drop_column('signup_otp', 'id')
